CIP-6288: Update pipeline config

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -50,3 +50,52 @@ include:
 # .post step finalisers eg: badges
   - project: 'ska-telescope/templates-repository'
     file: 'gitlab-ci/includes/finaliser.gitlab-ci.yml'
+
+python-test:
+  before_script:
+    - '[ -f .make/python.mk ] || (echo "File python.mk not included in Makefile; exit 1")'
+    - 'make help | grep python-test'
+    - poetry config virtualenvs.in-project true
+    - echo "python-build Setting.. poetry config virtualenvs.create true"
+    - poetry config virtualenvs.create true
+    - |
+      if [[ -f pyproject.toml ]]; then
+        echo "python-test: Installing with poetry";
+        poetry env use python3.12;
+        time poetry install;
+      else
+        if  [[ -f requirements.txt ]]; then
+          echo "python-test: Installing with pip";
+          time pip3 install -r requirements.txt;
+        fi;
+      fi;
+
+python-lint:
+  before_script:
+    - '[ -f .make/python.mk ] || (echo "File python.mk not included in Makefile"; exit 1;)'
+    - 'make help | grep python-lint'
+    - poetry config virtualenvs.in-project true
+    - echo "python-build Setting.. poetry config virtualenvs.create true"
+    - poetry config virtualenvs.create true
+    - |
+      if [[ -f pyproject.toml ]]; then
+        if [[ -n $CI_POETRY_VERSION ]]; then
+          # Check installed Poetry version
+          CURRENT_POETRY_VERSION=$(poetry --version | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
+          echo "python-lint: Installed Poetry version: $CURRENT_POETRY_VERSION, Required: $CI_POETRY_VERSION"
+          # Compare versions
+          if [[ $(printf '%s\n' "$CURRENT_POETRY_VERSION" "$CI_POETRY_VERSION" | sort -V | head -n1) != "$CI_POETRY_VERSION" ]]; then
+            echo "python-lint: Updating poetry to $CI_POETRY_VERSION";
+            pipx uninstall poetry && pipx install poetry==$CI_POETRY_VERSION;
+          fi;
+        fi;
+
+        echo "python-lint: Installing with poetry";
+        poetry env use python3.12;
+        time poetry install --all-extras;
+      else
+        if  [[ -f requirements.txt ]]; then
+          echo "python-lint: Installing with pip";
+          time pip3 install -r requirements.txt;
+        fi;
+      fi;
